Select * from [The_Local_Loft].[dbo] .[Loyalty_Program_Dataset_5000]

Select Distinct RewardName from [The_Local_Loft].[dbo] .[Loyalty_Program_Dataset_5000]
where RewardName not like '%NULL%'


Select Distinct CustomerID
From [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]

Select CustomerID
From [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]

Select Tier, AmountSpent
From [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
Where Tier ='Platinum'
--Basic SQL
--1.[BASIC FILTER] Retrieve all loyalty program records for customers in the Gold membership tier.
Select FirstName, LastName, Tier
from [The_Local_Loft].[dbo] .[Loyalty_Program_Dataset_5000]
Where Tier ='Gold'

--2.[BASIC FILTER] Find all transactions where AmountSpent is greater than 500.00 and the customer earned more than 500 loyalty points. 
Select FirstName, LastName,AmountSpent, PointsEarned
from [The_Local_Loft].[dbo] .[Loyalty_Program_Dataset_5000]
Where cast(AmountSpent as decimal (10,2)) > 500
Group by FirstName, LastName, AmountSpent, PointsEarned

--3.[SORTING] Retrieve TransactionID, CustomerID, AmountSpent, and PointsEarned for the top 10 highest-value purchases, ordered from highest to lowest. 
Select top 10 TransactionID, CustomerID, AmountSpent, PointsEarned
from [The_Local_Loft].[dbo] .[Loyalty_Program_Dataset_5000]
order by PointsEarned desc

--4.[DISTINCT VALUES] List all unique membership tiers available in the loyalty program. 
Select distinct tier
from [The_Local_Loft].[dbo] .[Loyalty_Program_Dataset_5000]

--5.[WHERE & LIKE] Retrieve all customers whose email address contains 'smith', sorted alphabetically by last name. 
Select FirstName, LastName, Email
from [The_Local_Loft].[dbo] .[Loyalty_Program_Dataset_5000]
where Email like '%smith%'
Order by LastName

--6.[AGGREGATION] Calculate the total revenue (SUM of AmountSpent) generated across all customer transactions. 
Select CustomerID, sum(cast(AmountSpent as decimal (10,2))) as total_per_customer
from [The_Local_Loft].[dbo] .[Loyalty_Program_Dataset_5000]
group by CustomerID

--7.[GROUP BY] Calculate the total revenue generated by each membership tier, ordered from highest revenue to lowest. 
Select Tier, sum(cast(AmountSpent as decimal (10,2))) as Total_Per_Tier
from [The_Local_Loft].[dbo] .[Loyalty_Program_Dataset_5000]
Group by Tier

--8.[GROUP BY & COUNT] Count the number of customers in each membership tier (Bronze, Silver, Gold, Platinum). 
Select count(Tier) as Number_Per_Tier
from [The_Local_Loft].[dbo] .[Loyalty_Program_Dataset_5000]
Group by Tier

--9.[GROUP BY & AVG] Calculate the average amount spent by customers in each membership tier, sorted from highest to lowest. 
Select Tier, avg(cast(AmountSpent as decimal (10,2))) as AVG_Per_Tier
from [The_Local_Loft].[dbo] .[Loyalty_Program_Dataset_5000]
Group by Tier
Order by AVG_Per_Tier Desc

--10.[GROUP BY & SUM] Calculate the total number of loyalty points earned by customers in each membership tier. 
Select Tier, sum(cast(PointsEarned as int)) as Points_Per_Customer
from [The_Local_Loft].[dbo] .[Loyalty_Program_Dataset_5000]
Group By Tier

--11.[WHERE & GROUP BY] Calculate the total revenue generated by customers who have redeemed at least one reward, grouped by RewardName. 
Select RewardName,PointsUsed, sum(cast(AmountSpent as decimal (10,2))) as Total_per_Customer
from [The_Local_Loft].[dbo] .[Loyalty_Program_Dataset_5000]
where cast(PointsUsed as decimal(10,2)) >=500
group by RewardName,PointsUsed

--12.[GROUP BY MULTIPLE] Calculate the total amount spent grouped by membership tier and RewardName. 
Select Tier, RewardName,sum(cast(AmountSpent as decimal(10,2))) as Total_Per_Tier
from [The_Local_Loft].[dbo] .[Loyalty_Program_Dataset_5000]
group by Tier, RewardName

--13.[HAVING CLAUSE] List membership tiers that have generated more than 500,000 in total sales revenue, ordered by revenue descending. 
Select Tier, sum(cast(AmountSpent as decimal (10,2))) as Total_Revenue
from [The_Local_Loft].[dbo] .[Loyalty_Program_Dataset_5000]
Group by AmountSpent, Tier
having sum(Cast(AmountSpent as decimal(10,2))) >500
Order By Total_Revenue Desc

--14.[HAVING CLAUSE] Find rewards that have been redeemed by more than 100 customers, ordered by redemption count descending. 
Select RewardName, COUNT(*) AS Redemption_Count
From [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
Where RewardName not like '%NULL%'
Group by RewardName
Having COUNT(*) > 100
Order by Redemption_Count desc

--15.[HAVING CLAUSE] Identify customers (CustomerID) who have spent more than 3,000 in total across all their transactions, ordered from highest spender to lowest
Select CustomerID, Sum(Cast(AmountSpent as decimal (10,2))) as Revenue
From [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
Group By CustomerID
Having Sum(Cast(AmountSpent as decimal (10,2))) >3000
order by Revenue Desc

--Intermediate SQL
--16.[GROUP BY & COUNT] Calculate the number of transactions made by each customer and display the results from the most active customer to the least active.
Select Distinct CustomerID, count(TransactionID) as Transaction_per_Customer
From [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
Group by CustomerID
Order by Transaction_per_Customer Desc

--17.[GROUP BY & AVG] Calculate the average PointsEarned per transaction for each membership tier.
Select Tier,avg(cast(PointsEarned as decimal(10,2))) as AVG_Points_Per_Tier
From [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
Group By Tier

--18.[GROUP BY & SUM] Calculate the total PointsUsed for each reward and identify which reward has had the most loyalty points redeemed.
Select RewardName, sum(cast(PointsUsed as decimal (10,2))) as Points_Redeemed_Per_Reward
From [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
where RewardName not like '%NULL%'
Group by RewardName
Order by Points_Redeemed_Per_Reward Desc

--19.[WHERE & ORDER BY] Retrieve all transactions where AmountSpent is between 100.00 and 500.00, ordered from highest to lowest purchase amount.
Select AmountSpent
From [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
Where Cast(AmountSpent as decimal(10,2)) between 100 and 500
Order by AmountSpent desc

--20.[COUNT & WHERE] Count how many customers have never redeemed a reward.
Select Count(*) as No_Points_Used
From [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
Where PointsUsed is NULL

--21.[GROUP BY & MAX] Find the highest single transaction amount for each membership tier.
Select Tier,Max(cast(AmountSpent as decimal(10,2))) as Max_per_Tier
From [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
Group by Tier

--22.[GROUP BY & MIN] Find the lowest single transaction amount for each membership tier.
Select tier, min(cast(AmountSpent as decimal(10,2))) as Min_per_Tier
From [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
Group by Tier

--23.[GROUP BY & SUM] Calculate the total AmountSpent and total PointsEarned for each customer.
Select distinct CustomerID, sum(cast(AmountSpent as decimal(10,2))) as Total_Spent_Per_Customer, sum(cast(PointsEarned as decimal(10,2))) as Total_Earned_Per_Customer
From [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
Group by CustomerID

--24.[MULTIPLE CONDITIONS] Retrieve all Platinum customers who have made a transaction greater than 1,000.00.
Select Tier,AmountSpent
From [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
Where Tier ='Platinum' and cast(AmountSpent as decimal (10,2)) >1000

--25.[DISTINCT & WHERE] List the unique RewardName values that have actually been redeemed by customers.
Select distinct CustomerID,RewardName,PointsUsed
From [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
where PointsUsed is not null and RewardName is not null

--26.[GROUP BY & COUNT] Count the number of reward redemptions for each membership tier.
Select Tier, count(PointsUsed) as Points_Used_Per_Tier
From [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
Where PointsUsed is not null
Group by Tier

--27.[GROUP BY & AVG] Calculate the average AmountSpent for customers who redeemed a reward compared with customers who did not redeem a reward.
Select avg(cast(AmountSpent as decimal(10,2))) as AVG_Amount_Spent, RewardName
From [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
Group By RewardName

--28.[ORDER BY & TOP] Identify the top 20 customers based on their total amount spent across all transactions.
Select top 20  Sum(cast(AmountSpent as decimal(10,2))) as Total_amount_spent, CustomerID
From [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
Group by CustomerID
Order by Total_amount_spent Desc

--29.[GROUP BY & HAVING] Find customers who have completed at least 3 transactions and have spent more than 1,000.00 in total.
Select CustomerID, sum(Cast(AmountSpent as decimal (10,2))) as Transactions_Per_Customer, count(*) as total_per_customer
From [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
Group by CustomerID
Having count(*) >=3 and sum(Cast(AmountSpent as decimal (10,2))) >1000

--30.[GROUP BY & HAVING] Identify membership tiers where the average CurrentPoints balance is greater than 5,000 points, ordered from the highest average balance to the lowest.
Select Tier, avg(cast(CurrentPoints as decimal(10,2))) as Avg_Per_Tier_above_5000
From [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
Group by Tier
Having avg(cast(CurrentPoints as decimal(10,2))) >5000
Order by Avg_Per_Tier_above_5000 desc

-- Advanced SQL
--31.[GROUP BY & SUM] Calculate the total revenue generated by each customer and display only customers whose total spending exceeds 2,500.
Select CustomerID, sum(cast(AmountSpent as decimal(10,2))) as Total_Per_Customer
From [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
Group by CustomerID
Having sum(cast(AmountSpent as Decimal (10,2))) >2500

--32.[GROUP BY & COUNT] Determine how many unique customers have made purchases in the loyalty program.
Select distinct CustomerID, Count(TransactionID) as Purchases_Per_Customer
From [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
Group by CustomerID
Order by Purchases_Per_Customer

--33.[GROUP BY & AVG] Calculate the average CurrentPoints balance for each membership tier.
Select Tier, avg(cast(CurrentPoints as decimal(10,2))) as Average_Per_Customer
From [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
Group by Tier

--34[MAX & MIN] Find the customer with the highest CurrentPoints balance and the customer with the lowest CurrentPoints balance.
Select Max(cast(CurrentPoints as Decimal (10,2))) as Highest, Min(cast(CurrentPoints as decimal(10,2))) as Lowest
From [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]

--35.[GROUP BY & SUM] Calculate the total AmountSpent and PointsEarned for each month based on PurchaseDate.
Select PurchaseDate, Sum(cast(AmountSpent as Decimal (10,2))) As Amount_Spent_PM, Sum(Cast(PointsEarned as Decimal (10,2))) as Points_Earned_PM
From [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
Group by PurchaseDate

--36.[GROUP BY & COUNT] Determine the number of transactions made during each month and identify the month with the highest number of transactions.
Select Count(TransactionID) as Transactions_PM, PurchaseDate
From [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
Group By PurchaseDate
Order by Transactions_PM Desc

--37.[GROUP BY & SUM] Calculate the total revenue generated by each RewardName, based on the spending of customers who redeemed that reward.
Select Distinct RewardName,sum(cast(AmountSpent as decimal (10,2))) as Revenue_Per_Reward
From [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
where RewardName is not null
Group by RewardName
Order by Revenue_Per_Reward desc

--38.[WHERE & GROUP BY] Calculate the average transaction value for Bronze, Silver, Gold, and Platinum customers separately, considering only transactions above 100.00.
Select Tier, avg(cast(AmountSpent as decimal (10,2))) as Transaction_Amount_PT
From [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
Where cast(AmountSpent as decimal(10,2)) >100
Group By Tier

--39.[GROUP BY & HAVING] Identify customers who have earned more than 2,000 loyalty points across all their transactions.
Select CustomerID, Sum(Cast(PointsEarned as decimal (10,2))) as More_Than_2k
From [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
Group by CustomerID
Having Sum(Cast(PointsEarned as decimal (10,2))) >2000
Order by More_Than_2k Desc

--40.[GROUP BY & HAVING] Identify customers who have redeemed rewards worth more than 2,000 total points.
Select CustomerID, sum(cast(PointsUsed as Decimal(10,2))) as More_then_2k_Points_Used
From [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
Group by CustomerID
Having Sum(Cast(PointsUsed as Decimal(10,2))) >2000
Order by More_then_2k_Points_Used Desc

--41.[SUBQUERY] Find customers whose total spending is higher than the overall average customer spending.
Select CustomerID, sum(cast(AmountSpent as decimal(10,2))) as Total_Spent,
(select avg(Total_Spent)
from (select CustomerID,sum(cast(AmountSpent as decimal(10,2))) as Total_Spent
from [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
Group by CustomerID) as CustomerTotals) as Average_Customer_Spend
from [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
group by CustomerID
having sum(cast(AmountSpent as decimal(10,2))) >
(select avg(Total_Spent)
from(select CustomerID, sum(cast(AmountSpent as decimal(10,2))) as Total_Spent
from [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
group by CustomerID) as CustomerTotals)
order by Total_Spent desc;

--42.[SUBQUERY] Find the customers whose CurrentPoints balance is greater than the average CurrentPoints balance of all customers.
Select CustomerID, sum(cast(CurrentPoints as decimal(10,2))) as Total_Points,
(select avg(Total_Points)
from (select CustomerID,sum(cast(CurrentPoints as decimal(10,2))) as Total_Points
from [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
Group by CustomerID) as CustomerTotals) as Average_Customer_Points
from [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
group by CustomerID
having sum(cast(CurrentPoints as decimal(10,2))) >
(select avg(Total_Points)
from(select CustomerID, sum(cast(CurrentPoints as decimal(10,2))) as Total_Points
from [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
group by CustomerID) as CustomerTotals)
order by Total_Points desc;

--43.[CASE STATEMENT] Create a new customer spending category using CASE: Low Spender for totals below 500, Medium Spender for 500–2,499, and High Spender for 2,500 or more.
Select CustomerID, Sum(Cast(AmountSpent as decimal (10,2))) as TotalSpending,
Case
When sum(cast(AmountSpent as decimal (10,2))) <500 then 'Low Spend'
When sum(cast(AmountSpent as decimal (10,2))) between 500 and 2499 then 'Medium Spend'
When sum(cast(AmountSpent as decimal(10,2))) >2500 then 'High Spend'
End as Spending
from [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
Group by CustomerID
Order by TotalSpending Desc
--44.[CASE STATEMENT] Create a loyalty engagement category based on CurrentPoints: New Member for fewer than 500 points, Active Member for 500–4,999 points, and VIP Member for 5,000 or more points.
Select CustomerID, Cast(CurrentPoints as decimal (10,2)) as CurrentPoints,
Case
When cast(CurrentPoints  as decimal (10,2)) <500 then 'New Member'
When cast(CurrentPoints as decimal (10,2)) between 500 and 4999 then 'Active Member'
When cast(CurrentPoints as decimal(10,2)) >5000 then 'VIP Member'
End as Engagment
from [The_Local_Loft].[dbo].[Loyalty_Program_Dataset_5000]
Group by CustomerID, CurrentPoints
Order by Engagment Desc

--45.[JOIN / RELATIONSHIP] Using the customer and transaction data, calculate the total number of transactions, total amount spent, and total points earned for each customer, including customers who have no transactions.
Select 
A.CustomerID,
A.JoinDate, 
Count(A.TransactionID) as Total_Transactions, 
A.PurchaseDate, 
Sum(try_Cast(A.AmountSpent as decimal (10,2))) as Total_Spent,
B.FirstName, 
B.LastName, 
B.Email, 
B.Phone, 
B.Tier, 
B.CurrentPoints, 
Sum(try_Cast(B.PointsEarned as decimal (10,2))) as Total_Points, 
B.RewardID,
B.RewardName, 
B.PointsRequired, 
B.RedemptionDate,
B.PointsUsed
From [The_Local_Loft].[dbo].[Purchases] A
Left join [The_Local_Loft].[dbo].[Customer_Info] B
on A.CustomerID=B.CustomerID
Group by A.CustomerID,A.JoinDate,A.PurchaseDate,B.FirstName, B.LastName, B.Email, B.Phone, B.Tier, B.CurrentPoints, B.RewardID,B.RewardName, B.PointsRequired, B.RedemptionDate,B.PointsUsed;